## Secret to be used as MinIO Root Credentials
apiVersion: v1
kind: Secret
metadata:
  name: minio-creds-secret
type: Opaque
data:
  ## Access Key for MinIO Tenant, base64 encoded (echo -n 'minio' | base64)
  accesskey: bWluaW8=
  ## Secret Key for MinIO Tenant, base64 encoded (echo -n 'minio123' | base64)
  secretkey: bWluaW8xMjM=
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-user1
type: Opaque
data:
  ## Access Key for MinIO Tenant
  accesskey: QUtJQUlPU0ZPRE5ON0VYQU1QTEU=
  ## Secret Key for MinIO Tenant
  secretkey: d0phbHJYVXRuRkVNSS9LN01ERU5HL2JQeFJmaUNZRVhBTVBMRUtFWQ==