kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 8011
    protocol: TCP
  - containerPort: 443
    hostPort: 4431
    protocol: TCP
- role: worker
- role: worker
  #image: datdrone/kind_node_gpu:v1.21.1
  #args:
  #  - "--gpus=all"