apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-endpoint-configmap
  annotations:
    kubed.appscode.com/sync: "true"
data:
  minio_endpoint: basic-minio-service.basic-minio.svc.cluster.local
  minio_service_port: "9000"