apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: metastore
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha:centos8-13.4-0
  postgresVersion: 13
  instances:
    - dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 4Gi
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.33-2
      repoHost:
        dedicated: {}
      configuration:
      - secret:
          name: pgo-s3-creds2
      global:
        repo1-path: /pgbackrest/postgres-operator/metastore-s3/repo1
      repos:
      - name: repo1
        s3:
          bucket: "metastore-pg"
          endpoint: "minio.minio-tenant.svc.cluster.local"
          region: ""