apiVersion: k3d.io/v1alpha2
kind: Simple
servers: 1
agents: 4
image: datadrone/k3d-gpu:v1.21.3-k3s1-cuda-11-2
ports:
  - port: 8081:80
    nodeFilters:
      - loadbalancer
volumes:
  - volume: /opt/data/common-storage:/data
    nodeFilters:
      - agent[*]
  - volume: /opt/data/minio/drive1:/store
    nodeFilters:
      - agent[0]
  - volume: /opt/data/minio/drive2:/store
    nodeFilters:
      - agent[1]
  - volume: /opt/data/minio/drive3:/store
    nodeFilters:
      - agent[2]
  - volume: /opt/data/minio/drive4:/store
    nodeFilters:
      - agent[3]
registries:
  create: true
options:
  k3s:
    extraServerArgs:
      - --no-deploy=traefik
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
  runtime:
    gpuRequest: all