apiVersion: v1
kind: ConfigMap
metadata:
  name: create-minio-bucket-script
  namespace: mlflow
data:
  job.sh: |
    #!/bin/sh
    set -ex

    mc config host add minio http://$MINIO_ENDPOINT:$MINIO_PORT $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
    mc mb --ignore-existing minio/mlflow
---
apiVersion: batch/v1
kind: Job
metadata:
  name: minio-job
  namespace: mlflow
spec:
  template:
    spec:
      volumes:
      - name: scripts
        configMap:
          name: create-minio-bucket-script
          defaultMode: 0777
      containers:
      - name: create-minio-bucket-script
        image: minio/mc:RELEASE.2021-10-07T04-19-58Z
        command: ["sh", "-c"]
        args: ["/setup/job.sh"]
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - name: scripts
          mountPath: /setup/job.sh
          subPath: job.sh
        env:
        - name: MINIO_ENDPOINT
          valueFrom: { configMapKeyRef: { name: minio-endpoint-configmap, key: minio_endpoint } }
        - name: MINIO_PORT
          valueFrom: { configMapKeyRef: { name: minio-endpoint-configmap, key: minio_service_port } }
        - name: MINIO_ACCESS_KEY
          valueFrom: { secretKeyRef: { name: minio-secret, key: minio-root-user } }
        - name: MINIO_SECRET_KEY 
          valueFrom: { secretKeyRef: { name: minio-secret, key: minio-root-password } }
      restartPolicy: Never
  backoffLimit: 0