hub:
  baseUrl: /jupyter
  config:
    KubeSpawner:
      service_account: spark

singleuser:
  image:
    name: datadrone/deeplearn_minimal
    tag: cuda-11.1-base
  defaultUrl: "/lab"
  storage:
    dynamic:
      storageClass: local-path