hub:
  baseUrl: /jupyter
  config:
    KubeSpawner:
      service_account: spark

proxy:
  service:
    type: ClusterIP

singleuser:
  image:
    name: jupyter/minimal-notebook
    tag: latest
  profileList:
    - display_name: "Default Minimal"
      description: "Simple Base"
      default: true
    - display_name: "GPU Environment"
      description: "GPU enabled session"
      kubespawner_override:
        image: datadrone/deeplearn_minimal
        tag: cuda-11.1-base
        extra_annotations:
          gpu-fraction: "1"
    - display_name: "GPU Spark Environment"
      description: "GPU enabled spark session"
      kubespawner_override:
        image: k3d-test-registry:5000/datadrone/spark_notebook_kube
        tag: latest
        extra_annotations:
          gpu-fraction: "1"
  defaultUrl: "/lab"
  storage:
    dynamic:
      storageClass: local-path

prePuller:
  extraImages:
    gpuimage:
      name: k3d-test-registry:5000/datadrone/deeplearn_minimal
      tag: cuda-11.1-base
    gpusparkimage:
      name: k3d-test-registry:5000/datadrone/spark_notebook_kube
      tag: latest