hub:
  baseUrl: /jupyter
  config:
    KubeSpawner:
      service_account: spark

proxy:
  service:
    type: ClusterIP

singleuser:
  image:
    name: k3d-test-registry:5000/datadrone/minimal-notebook-env
    tag: latest
    pullPolicy: "Always"
  profileList:
    - display_name: "Default Minimal"
      description: "Simple Base"
      default: true
    - display_name: "GPU Environment"
      description: "GPU enabled session"
      kubespawner_override:
        image: datadrone/deeplearn_minimal
        tag: cuda-11.1-base
        extra_annotations:
          gpu-fraction: "1"
    - display_name: "GPU Spark Environment"
      description: "GPU enabled spark session"
      kubespawner_override:
        image: k3d-test-registry:5000/datadrone/k8s-spark-notebook
        tag: latest
        image_pull_policy: 'Always'
        extra_annotations:
          gpu-fraction: "1"
  defaultUrl: "/lab"
  networkPolicy:
    enabled: true
    allowedIngressPorts: [2222, 7777] 
  storage:
    dynamic:
      storageClass: local-path

prePuller:
  hook:
    enabled: true
  extraImages:
    sparkworkerimage:
      name: k3d-test-registry:5000/datadrone/k8s-spark-worker
      tag: 3.1.2-hadoop3.2-rapids-k8s-basic
    gpusparkworkerimage:
      name: k3d-test-registry:5000/datadrone/k8s-spark-worker
      tag: 3.1.2-hadoop3.2-rapids-k8s
      