apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: jhub
  labels:
    component: jupyter
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spark
  namespace: jhub
  labels:
    component: jupyter
rules:
  - apiGroups: [""]       # "" indicates the core API group
    resources: ["pods", "configmaps"]
    verbs: ["get", "watch", "list", "create", "delete", "patch"] 
  - apiGroups: [""]       # "" indicates the core API group
    resources: ["events"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spark
  namespace: jhub
  labels:
    component: jupyter
subjects:
  - kind: ServiceAccount
    name: spark
    namespace:
roleRef:
  kind: Role
  name: spark
  apiGroup: rbac.authorization.k8s.io